### ISSUE TITLE
关于Tag子元素溢出部分在拖动时无法显示的问题

### ISSUE THREAD

**Issue by SugaraguS** [bolan9999/react-native-drag-to-sort-tags#1]
你好，我在实现您的例子的时候，在_renderTag()方法中添加了一个图标，显示在了tag的右上角，在拖动tag的时候overflow的那部分没有显示出来，请问这个该怎么解决呢？萌新求教
```
import MaterialIcon from 'react-native-vector-icons/MaterialCommunityIcons';
...
_renderTag = (tag: string) => {
    return (
      <View style={styles.button}>
        <Text style={styles.text}>{tag}</Text>
        <MaterialIcon
          name="close-circle"
          size={20}
          color="#D3D3D3"
          style={{ position: 'absolute', top: -7, right: -7 }}
        />
      </View>
    );
  };
```
![tim 20181010140738](https://user-images.githubusercontent.com/7043862/46716277-f48ee900-cc95-11e8-9170-7bb34f6b7ce6.jpg)
![tim 20181010140813](https://user-images.githubusercontent.com/7043862/46716285-fa84ca00-cc95-11e8-84d4-84dcddbd5d40.jpg)

**Comment by ATShiTou** [comment]
这个是RN的bug。

你可以选择扩大Tag的范围，不让右上角的超出边界。 具体就是让styles.text 加上marginRight：7,marginTop:7，再调整删除按钮的位置
